# This is a basic workflow to help you get started with Actions

name: Check & Notify

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2,8,14,20 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    name: Check & Notify
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetching mastodon.social
        id: fetch
        env:
          INSTANCE: 'mastodon.social'
        run: |
          STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}" https://$INSTANCE/auth/sign_up`
          echo "STATUS_CODE='$STATUS_CODE'" >> $GITHUB_OUTPUT
      
      - name: Print Responce code
        id: print
        run: echo "Responce code is ${{ steps.fetch.outputs.STATUS_CODE }}."
      
      - name: Notify Open
        id: notify-open
        if: ${{ steps.fetch.outputs.STATUS_CODE == '200' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
               -H "Content-Type: application/json" \
               -d "{\"chat_id\":\"$TELEGRAM_CHAT_ID\",\"parse_mode\":\"MarkdownV2\",\"text\":\"\`$INSTANCE\` is now *OPEN* for signing up\\\\! \\\\(via GitHub Action\\\\)\""
      
      - name: Notify Closed
        id: notify-closed
        if: ${{ steps.fetch.outputs.STATUS_CODE != '200' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
               -H "Content-Type: application/json" \
               -d "{\"chat_id\":\"$TELEGRAM_CHAT_ID\",\"parse_mode\":\"MarkdownV2\",\"text\":\"\`$INSTANCE\` is still closed for singing up\\\\. \\\\(via GitHub Action\\\\)\""
